apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oxubaj4zq-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oxubaj4zq-nodejs 
  name: oxubaj4zq-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: oxubaj4zq-nodejs 
